theme: jekyll-theme-cayman

title: Too much tooty in the fruity Keeping food safe in a post-Brexit Britain
subtitle: hello
description: Data challenge organised by the Jean Golding Institute at the University of Bristol and the Food Standard Agency (FSA)
site_url: https://mvab.github.io/JGI-food-hazards-viz-challenge/
